[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["jembe"]
branch = true

[tool.djlint]
format_attribute_template_tags=true
format_js=true

[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"
